### ISSUE TITLE
[Release: 0.2.0] 추가 기능 명세

### ISSUE THREAD

**Issue by J0onYEong** [J0onYEong/Junimofire#2]
## TODO
- [x] 특정 세션의 요청에 기본적으로 적용되는 Adapter가 있다.
- [x] 특정 세션의 요청에 기본적으로 적용되는 Retrier가 있다.
- [x] 특정 세션의 요청에 기본적으로 적용되는 Validator가 있다.
